# Site settings
title: David Yang 블로그
url: "https://davidyang2149.github.io"
baseurl: ""
description: >
    David Yang 블로그

# My information
email: davidyang2149@gmail.com
author: David Yang
profile: 가족 신뢰 성장
github_username: davidyang2149
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
giscus:
  repo: davidyang2149/davidyang2149.github.io
  repo_id: R_kgDOIi0gLg
  category: Announcements
  category_id: DIC_kwDOIi0gLs4CThuy

google_analytics:
  ua: G-19R92080ZM
  encrypted_ua: 4ea6b4b353f6a470e8c2697cPbkRUQTRUBsQvMY0NSk6BqwuBQGWDkEYsmoF3w==

google_adsense:
  client: SAMPLE-VALUE

blame: "https://github.com/DavidYang2149/davidyang2149.github.io/blame/main/_wiki"
edit: "https://github.com/DavidYang2149/davidyang2149.github.io/edit/main/_wiki"
issue: "https://github.com/DavidYang2149/davidyang2149.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
